package Formularios;



import controladores.LaboratorioJpaController;
import Entidades.Laboratorio;
import java.awt.Color;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author APRENDIZ
 */
public class frmlaboratorios extends javax.swing.JDialog {
LaboratorioJpaController lc = new LaboratorioJpaController();
    /**
     * Creates new form frmlaboratorios
     */
    public frmlaboratorios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        descripcion = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        bgbuscar3 = new javax.swing.JPanel();
        btnbuscar3 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        bgagregar3 = new javax.swing.JPanel();
        btnagregar3 = new javax.swing.JLabel();
        bgeliminar3 = new javax.swing.JPanel();
        btneliminar3 = new javax.swing.JLabel();
        bgeditar3 = new javax.swing.JPanel();
        btneditar3 = new javax.swing.JLabel();
        bgguardar3 = new javax.swing.JPanel();
        btnguardar3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla3 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(2, 165, 156));
        jLabel1.setText("Descripcion:");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(2, 165, 156));
        jLabel2.setText("Direccion:");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(2, 165, 156));
        jLabel3.setText("Telefono:");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(2, 165, 156));
        jLabel4.setText("Email:");

        descripcion.setBackground(new java.awt.Color(255, 255, 255));
        descripcion.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        descripcion.setForeground(new java.awt.Color(0, 0, 0));

        direccion.setBackground(new java.awt.Color(255, 255, 255));
        direccion.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        direccion.setForeground(new java.awt.Color(0, 0, 0));

        bgbuscar3.setBackground(new java.awt.Color(2, 165, 156));

        btnbuscar3.setBackground(new java.awt.Color(255, 255, 255));
        btnbuscar3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnbuscar3.setForeground(new java.awt.Color(255, 255, 255));
        btnbuscar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnbuscar3.setText("Buscar");
        btnbuscar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbuscar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbuscar3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbuscar3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout bgbuscar3Layout = new javax.swing.GroupLayout(bgbuscar3);
        bgbuscar3.setLayout(bgbuscar3Layout);
        bgbuscar3Layout.setHorizontalGroup(
            bgbuscar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnbuscar3, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
        );
        bgbuscar3Layout.setVerticalGroup(
            bgbuscar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnbuscar3, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        telefono.setBackground(new java.awt.Color(255, 255, 255));
        telefono.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        telefono.setForeground(new java.awt.Color(0, 0, 0));
        telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoKeyTyped(evt);
            }
        });

        email.setBackground(new java.awt.Color(255, 255, 255));
        email.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        email.setForeground(new java.awt.Color(0, 0, 0));

        bgagregar3.setBackground(new java.awt.Color(2, 165, 156));

        btnagregar3.setBackground(new java.awt.Color(255, 255, 255));
        btnagregar3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnagregar3.setForeground(new java.awt.Color(255, 255, 255));
        btnagregar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnagregar3.setText("Agregar");
        btnagregar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnagregar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnagregar3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnagregar3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout bgagregar3Layout = new javax.swing.GroupLayout(bgagregar3);
        bgagregar3.setLayout(bgagregar3Layout);
        bgagregar3Layout.setHorizontalGroup(
            bgagregar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnagregar3, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
        );
        bgagregar3Layout.setVerticalGroup(
            bgagregar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnagregar3, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        bgeliminar3.setBackground(new java.awt.Color(2, 165, 156));

        btneliminar3.setBackground(new java.awt.Color(255, 255, 255));
        btneliminar3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btneliminar3.setForeground(new java.awt.Color(255, 255, 255));
        btneliminar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btneliminar3.setText("Eliminar");
        btneliminar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneliminar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btneliminar3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btneliminar3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout bgeliminar3Layout = new javax.swing.GroupLayout(bgeliminar3);
        bgeliminar3.setLayout(bgeliminar3Layout);
        bgeliminar3Layout.setHorizontalGroup(
            bgeliminar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btneliminar3, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
        );
        bgeliminar3Layout.setVerticalGroup(
            bgeliminar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btneliminar3, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        bgeditar3.setBackground(new java.awt.Color(2, 165, 156));

        btneditar3.setBackground(new java.awt.Color(255, 255, 255));
        btneditar3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btneditar3.setForeground(new java.awt.Color(255, 255, 255));
        btneditar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btneditar3.setText("Editar");
        btneditar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneditar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btneditar3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btneditar3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout bgeditar3Layout = new javax.swing.GroupLayout(bgeditar3);
        bgeditar3.setLayout(bgeditar3Layout);
        bgeditar3Layout.setHorizontalGroup(
            bgeditar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btneditar3, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
        );
        bgeditar3Layout.setVerticalGroup(
            bgeditar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btneditar3, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        bgguardar3.setBackground(new java.awt.Color(2, 165, 156));

        btnguardar3.setBackground(new java.awt.Color(255, 255, 255));
        btnguardar3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnguardar3.setForeground(new java.awt.Color(255, 255, 255));
        btnguardar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnguardar3.setText("Guardar");
        btnguardar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnguardar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnguardar3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnguardar3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnguardar3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout bgguardar3Layout = new javax.swing.GroupLayout(bgguardar3);
        bgguardar3.setLayout(bgguardar3Layout);
        bgguardar3Layout.setHorizontalGroup(
            bgguardar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnguardar3, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
        );
        bgguardar3Layout.setVerticalGroup(
            bgguardar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnguardar3, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        tabla3.setBackground(new java.awt.Color(2, 165, 156));
        tabla3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tabla3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla3.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tabla3);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(2, 165, 156));
        jLabel5.setText("Codigo:");

        codigo.setBackground(new java.awt.Color(255, 255, 255));
        codigo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        codigo.setForeground(new java.awt.Color(0, 0, 0));
        codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bgagregar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(direccion, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(bgeliminar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34)
                                    .addComponent(bgeditar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bgguardar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(telefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(descripcion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(bgbuscar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bgbuscar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bgagregar3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bgeliminar3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bgeditar3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bgguardar3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void cargarTabla(){
        DefaultTableModel modelo = new DefaultTableModel();
        String nombreColumnas[] = {"Codigo","Descripcion","Telefono","Email","Direccion"};
        modelo.setColumnIdentifiers(nombreColumnas);
        
        List lista = lc.findLaboratorioEntities();
        for (int i = 0; i < lista.size(); i++) {
            Laboratorio p = (Laboratorio) lista.get(i);
            Object fila [] = {p.getCodigo(),p.getDescripcion(),p.getTelefono(),p.getEmail(),p.getDireccion()};
            modelo.addRow(fila);
        }
        
        tabla3.setModel(modelo);
    }
    
    private void btnbuscar3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscar3MouseEntered
        // TODO add your handling code here:
        bgbuscar3.setBackground(new Color(2,191,182));
    }//GEN-LAST:event_btnbuscar3MouseEntered

    private void btnbuscar3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscar3MouseExited
        // TODO add your handling code here:
        bgbuscar3.setBackground(new Color(2,165,156));
    }//GEN-LAST:event_btnbuscar3MouseExited

    private void btnagregar3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnagregar3MouseEntered
        // TODO add your handling code here:
        bgagregar3.setBackground(new Color(2,191,182));
    }//GEN-LAST:event_btnagregar3MouseEntered

    private void btnagregar3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnagregar3MouseExited
        // TODO add your handling code here:
        bgagregar3.setBackground(new Color(2,165,156));
    }//GEN-LAST:event_btnagregar3MouseExited

    private void btneliminar3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneliminar3MouseEntered
        // TODO add your handling code here:
        bgeliminar3.setBackground(new Color(2,191,182));
    }//GEN-LAST:event_btneliminar3MouseEntered

    private void btneliminar3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneliminar3MouseExited
        // TODO add your handling code here:
        bgeliminar3.setBackground(new Color(2,165,156));
    }//GEN-LAST:event_btneliminar3MouseExited

    private void btneditar3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditar3MouseEntered
        // TODO add your handling code here:
        bgeditar3.setBackground(new Color(2,191,182));
    }//GEN-LAST:event_btneditar3MouseEntered

    private void btneditar3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditar3MouseExited
        // TODO add your handling code here:
        bgeditar3.setBackground(new Color(2,165,156));
    }//GEN-LAST:event_btneditar3MouseExited

    private void btnguardar3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnguardar3MouseEntered
        // TODO add your handling code here:
        bgguardar3.setBackground(new Color(2,191,182));
    }//GEN-LAST:event_btnguardar3MouseEntered

    private void btnguardar3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnguardar3MouseExited
        // TODO add your handling code here:
        bgguardar3.setBackground(new Color(2,165,156));
    }//GEN-LAST:event_btnguardar3MouseExited

    private void telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_telefonoKeyTyped

    private void btnguardar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnguardar3MouseClicked
        // TODO add your handling code here:
        int codigo = Integer.parseInt(this.codigo.getText());
        String descripcion = this.descripcion.getText();
        String  telefono =this.telefono.getText();
        String email = this.email.getText();
        String direccion = this.direccion.getText();

        Laboratorio l = new Laboratorio(codigo,descripcion,direccion,telefono,email);
        LaboratorioJpaController cl = new LaboratorioJpaController();
        
        try {
            cl.create(l);
            JOptionPane.showMessageDialog(null, "Registro guardado correctamente");
            limpiar();
            cargarTabla();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Se presento un error al guardar");
        }
    }//GEN-LAST:event_btnguardar3MouseClicked

    private void codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_codigoKeyTyped

    public void limpiar(){
        codigo.setText("");
        descripcion.setText("");
        telefono.setText("");
        email.setText("");
        direccion.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmlaboratorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmlaboratorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmlaboratorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmlaboratorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmlaboratorios dialog = new frmlaboratorios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgagregar3;
    private javax.swing.JPanel bgbuscar3;
    private javax.swing.JPanel bgeditar3;
    private javax.swing.JPanel bgeliminar3;
    private javax.swing.JPanel bgguardar3;
    private javax.swing.JLabel btnagregar3;
    private javax.swing.JLabel btnbuscar3;
    private javax.swing.JLabel btneditar3;
    private javax.swing.JLabel btneliminar3;
    private javax.swing.JLabel btnguardar3;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField descripcion;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla3;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
